import type { Member, Milestone, Product, RoadmapItem } from "../types";

export const PRODUCTS: Product[] = [
  { key: "mobile", name: "Mobile App", icon: "Smartphone", color: "#3b82f6" },
  { key: "partner", name: "Partner Platform", icon: "Handshake", color: "#8b5cf6" },
  { key: "gateway", name: "Payment Gateway", icon: "CreditCard", color: "#10b981" },
  { key: "admin", name: "Admin Dashboard", icon: "ShieldCheck", color: "#f59e0b" },
  { key: "agents", name: "Agent Network", icon: "Users", color: "#14b8a6" },
  { key: "market", name: "Mizaniya Market", icon: "Store", color: "#ec4899" },
  // The following three exist as real "Product" field options in the
  // MizaniyaPay ClickUp workspace but aren't part of the original 6-product
  // seed set — only populated when synced live from ClickUp.
  { key: "market_admin", name: "Market Admin", icon: "Settings2", color: "#f97316" },
  { key: "website", name: "Website", icon: "Globe", color: "#0ea5e9" },
  { key: "mtp", name: "MTP", icon: "Landmark", color: "#64748b" },
];

export const MEMBERS: Member[] = [
  { id: "u1", name: "Rayen M.", initials: "RM", color: "#6366f1", team: "Product" },
  { id: "u2", name: "Amine K.", initials: "AK", color: "#0ea5e9", team: "Backend Team" },
  { id: "u3", name: "Sara B.", initials: "SB", color: "#f97316", team: "Backend Team" },
  { id: "u4", name: "Yacine T.", initials: "YT", color: "#22c55e", team: "Mobile Team" },
  { id: "u5", name: "Nadia F.", initials: "NF", color: "#ec4899", team: "Mobile Team" },
  { id: "u6", name: "Lina H.", initials: "LH", color: "#a855f7", team: "Design Team" },
  { id: "u7", name: "Karim S.", initials: "KS", color: "#eab308", team: "QA Team" },
  { id: "u8", name: "Yasmine D.", initials: "YD", color: "#14b8a6", team: "Frontend Team" },
];

const owner = (id: string): Member => MEMBERS.find((m) => m.id === id)!;

function iso(y: number, m: number, d: number): string {
  return new Date(Date.UTC(y, m - 1, d)).toISOString();
}

interface Seed {
  id: string;
  title: string;
  description: string;
  businessGoal: string;
  product: RoadmapItem["product"];
  team: string;
  ownerId: string;
  status: RoadmapItem["status"];
  priority: RoadmapItem["priority"];
  progress: number;
  start: [number, number, number];
  end: [number, number, number];
  version?: string;
  taskCount: number;
  dependencies?: string[];
}

const seeds: Seed[] = [
  // Mobile App
  {
    id: "mob-kyc",
    title: "KYC Level 1 Improvements",
    description: "Streamline the level-1 KYC flow with document auto-capture and liveness detection to cut onboarding drop-off.",
    businessGoal: "Reduce onboarding time from 6 min to under 2 min and lift KYC completion rate above 85%.",
    product: "mobile",
    team: "Mobile Team",
    ownerId: "u4",
    status: "in_progress",
    priority: "high",
    progress: 65,
    start: [2026, 10, 1],
    end: [2026, 10, 22],
    version: "v1.4",
    taskCount: 7,
  },
  {
    id: "mob-auth",
    title: "Authentication V2",
    description: "Biometric login, device binding and session hardening across Android and iOS.",
    businessGoal: "Cut account-takeover support tickets by 40%.",
    product: "mobile",
    team: "Mobile Team",
    ownerId: "u5",
    status: "in_progress",
    priority: "high",
    progress: 55,
    start: [2026, 10, 3],
    end: [2026, 10, 26],
    version: "v1.3",
    taskCount: 6,
  },
  {
    id: "mob-qr",
    title: "QR Payments",
    description: "Merchant QR scan-to-pay with offline fallback and instant confirmation.",
    businessGoal: "Grow in-store QR payment volume by 3x this quarter.",
    product: "mobile",
    team: "Mobile Team",
    ownerId: "u4",
    status: "review",
    priority: "high",
    progress: 78,
    start: [2026, 10, 1],
    end: [2026, 10, 24],
    version: "v1.3",
    taskCount: 5,
  },
  {
    id: "mob-cashtopup",
    title: "Cash Top Up Improvements",
    description: "Agent-assisted cash top-up with receipt scanning and real-time balance sync.",
    businessGoal: "Reduce top-up failure rate below 1%.",
    product: "mobile",
    team: "Mobile Team",
    ownerId: "u5",
    status: "todo",
    priority: "medium",
    progress: 15,
    start: [2026, 11, 3],
    end: [2026, 11, 21],
    version: "v1.4",
    taskCount: 4,
    dependencies: ["mob-qr"],
  },
  {
    id: "mob-notif",
    title: "Notification Center",
    description: "Unified in-app notification hub with transaction alerts and promo campaigns.",
    businessGoal: "Increase weekly active usage by improving re-engagement.",
    product: "mobile",
    team: "Mobile Team",
    ownerId: "u8",
    status: "in_progress",
    priority: "medium",
    progress: 40,
    start: [2026, 10, 12],
    end: [2026, 11, 5],
    version: "v1.4",
    taskCount: 5,
  },
  {
    id: "mob-esim",
    title: "eSIM V2",
    description: "In-app eSIM purchase and activation for partner mobile carriers.",
    businessGoal: "Launch a new revenue line via carrier partnerships.",
    product: "mobile",
    team: "Mobile Team",
    ownerId: "u4",
    status: "backlog",
    priority: "low",
    progress: 5,
    start: [2026, 12, 1],
    end: [2026, 12, 22],
    version: "v2.0",
    taskCount: 6,
  },
  {
    id: "mob-perf",
    title: "Performance Optimization",
    description: "Cold start time, bundle size and frame-drop reduction across both platforms.",
    businessGoal: "Bring cold start under 1.5s on mid-tier Android devices.",
    product: "mobile",
    team: "Mobile Team",
    ownerId: "u8",
    status: "todo",
    priority: "medium",
    progress: 10,
    start: [2026, 11, 20],
    end: [2026, 12, 15],
    version: "v1.4",
    taskCount: 4,
  },

  // Partner Platform
  {
    id: "prt-paylinks",
    title: "Payment Links",
    description: "Shareable one-time and recurring payment links for merchants without a full integration.",
    businessGoal: "Onboard 500+ long-tail merchants without dev effort.",
    product: "partner",
    team: "Backend Team",
    ownerId: "u2",
    status: "in_progress",
    priority: "high",
    progress: 60,
    start: [2026, 10, 1],
    end: [2026, 10, 25],
    version: "v1.4",
    taskCount: 6,
  },
  {
    id: "prt-vtpe",
    title: "VTPE Improvements",
    description: "Virtual TPE terminal reliability fixes and new receipt printing options.",
    businessGoal: "Reduce VTPE transaction failure rate for partner merchants.",
    product: "partner",
    team: "Backend Team",
    ownerId: "u3",
    status: "production",
    priority: "high",
    progress: 100,
    start: [2026, 10, 5],
    end: [2026, 10, 30],
    version: "v1.3",
    taskCount: 5,
  },
  {
    id: "prt-analytics",
    title: "Partner Analytics",
    description: "Self-serve dashboards for partners to track settlement, volume and chargebacks.",
    businessGoal: "Reduce partner support requests for statements by 50%.",
    product: "partner",
    team: "Frontend Team",
    ownerId: "u8",
    status: "todo",
    priority: "medium",
    progress: 20,
    start: [2026, 11, 2],
    end: [2026, 11, 28],
    version: "v1.4",
    taskCount: 5,
  },
  {
    id: "prt-merchant-mgmt",
    title: "Merchant Management",
    description: "Bulk merchant onboarding, KYB workflow and tiered fee configuration.",
    businessGoal: "Cut merchant onboarding turnaround from 5 days to 1.",
    product: "partner",
    team: "Backend Team",
    ownerId: "u2",
    status: "in_progress",
    priority: "high",
    progress: 50,
    start: [2026, 10, 15],
    end: [2026, 11, 12],
    version: "v1.4",
    taskCount: 7,
  },
  {
    id: "prt-withdrawal",
    title: "Withdrawal Management",
    description: "Automated partner withdrawal scheduling with configurable settlement windows.",
    businessGoal: "Give partners predictable settlement, reducing cash-flow support escalations.",
    product: "partner",
    team: "Backend Team",
    ownerId: "u3",
    status: "blocked",
    priority: "high",
    progress: 30,
    start: [2026, 11, 10],
    end: [2026, 12, 5],
    version: "v2.0",
    taskCount: 5,
    dependencies: ["prt-merchant-mgmt"],
  },
  {
    id: "prt-settlement",
    title: "Settlement",
    description: "T+1 settlement engine with reconciliation reports for finance.",
    businessGoal: "Move all partner settlement to T+1 by year end.",
    product: "partner",
    team: "Backend Team",
    ownerId: "u2",
    status: "todo",
    priority: "medium",
    progress: 12,
    start: [2026, 11, 25],
    end: [2026, 12, 18],
    version: "v2.0",
    taskCount: 6,
  },

  // Payment Gateway
  {
    id: "gw-satim",
    title: "SATIM Integration",
    description: "Direct routing integration with SATIM for local card acquiring.",
    businessGoal: "Enable local card acceptance without a third-party PSP.",
    product: "gateway",
    team: "Backend Team",
    ownerId: "u2",
    status: "in_progress",
    priority: "high",
    progress: 70,
    start: [2026, 10, 1],
    end: [2026, 10, 28],
    version: "v1.4",
    taskCount: 8,
  },
  {
    id: "gw-oneclick",
    title: "OneClick",
    description: "Tokenized one-click checkout for returning customers.",
    businessGoal: "Increase checkout conversion by reducing friction on repeat payments.",
    product: "gateway",
    team: "Backend Team",
    ownerId: "u3",
    status: "in_progress",
    priority: "high",
    progress: 55,
    start: [2026, 10, 8],
    end: [2026, 11, 2],
    version: "v1.4",
    taskCount: 5,
  },
  {
    id: "gw-webhooks",
    title: "Webhook Management",
    description: "Self-serve webhook configuration, retries and delivery logs for merchants.",
    businessGoal: "Reduce integration support tickets from merchant developers.",
    product: "gateway",
    team: "Backend Team",
    ownerId: "u2",
    status: "production",
    priority: "medium",
    progress: 100,
    start: [2026, 10, 12],
    end: [2026, 11, 3],
    version: "v1.4",
    taskCount: 4,
  },
  {
    id: "gw-apidocs",
    title: "API Documentation",
    description: "Public developer portal with interactive API reference and sandbox keys.",
    businessGoal: "Cut merchant integration time in half via self-serve docs.",
    product: "gateway",
    team: "Frontend Team",
    ownerId: "u8",
    status: "todo",
    priority: "low",
    progress: 18,
    start: [2026, 11, 5],
    end: [2026, 11, 26],
    version: "v1.4",
    taskCount: 3,
  },
  {
    id: "gw-reconciliation",
    title: "Reconciliation",
    description: "Automated daily reconciliation between gateway ledger and SATIM settlement files.",
    businessGoal: "Eliminate manual finance reconciliation work.",
    product: "gateway",
    team: "Backend Team",
    ownerId: "u3",
    status: "backlog",
    priority: "medium",
    progress: 5,
    start: [2026, 12, 1],
    end: [2026, 12, 20],
    version: "v2.0",
    taskCount: 5,
    dependencies: ["gw-satim"],
  },

  // Admin Dashboard
  {
    id: "adm-customer",
    title: "Customer Management",
    description: "360-degree customer profile view with transaction history and support notes.",
    businessGoal: "Reduce average support resolution time by 30%.",
    product: "admin",
    team: "Frontend Team",
    ownerId: "u8",
    status: "production",
    priority: "high",
    progress: 100,
    start: [2026, 10, 1],
    end: [2026, 10, 24],
    version: "v1.3",
    taskCount: 6,
  },
  {
    id: "adm-kycreview",
    title: "KYC Review",
    description: "Ops console for manual KYC review queue with document annotation tools.",
    businessGoal: "Cut manual KYC review time per case from 8 min to 3 min.",
    product: "admin",
    team: "Backend Team",
    ownerId: "u3",
    status: "in_progress",
    priority: "high",
    progress: 48,
    start: [2026, 10, 10],
    end: [2026, 11, 4],
    version: "v1.4",
    taskCount: 5,
  },
  {
    id: "adm-fraud",
    title: "Fraud Monitoring",
    description: "Rule-based transaction risk scoring with real-time alerting for ops.",
    businessGoal: "Reduce fraud losses by catching high-risk transactions before settlement.",
    product: "admin",
    team: "Backend Team",
    ownerId: "u2",
    status: "todo",
    priority: "high",
    progress: 22,
    start: [2026, 11, 1],
    end: [2026, 11, 25],
    version: "v1.4",
    taskCount: 6,
  },
  {
    id: "adm-agentmgmt",
    title: "Agent Management",
    description: "Admin console to manage agent network hierarchy, limits and commissions.",
    businessGoal: "Give ops full control over agent lifecycle without engineering involvement.",
    product: "admin",
    team: "Backend Team",
    ownerId: "u3",
    status: "in_progress",
    priority: "medium",
    progress: 38,
    start: [2026, 10, 18],
    end: [2026, 11, 14],
    version: "v1.4",
    taskCount: 5,
  },
  {
    id: "adm-reports",
    title: "Reports & Analytics",
    description: "Configurable reporting suite for finance, ops and executive stakeholders.",
    businessGoal: "Replace manual spreadsheet reporting for monthly business reviews.",
    product: "admin",
    team: "Frontend Team",
    ownerId: "u8",
    status: "todo",
    priority: "medium",
    progress: 15,
    start: [2026, 11, 20],
    end: [2026, 12, 16],
    version: "v2.0",
    taskCount: 6,
  },

  // Agent Network
  {
    id: "agt-onboarding",
    title: "Agent Onboarding Flow",
    description: "Digital agent application, document upload and approval workflow.",
    businessGoal: "Expand active agent network by 200 in Q4.",
    product: "agents",
    team: "Mobile Team",
    ownerId: "u5",
    status: "in_progress",
    priority: "high",
    progress: 52,
    start: [2026, 10, 6],
    end: [2026, 10, 29],
    version: "v1.4",
    taskCount: 5,
  },
  {
    id: "agt-commission",
    title: "Commission Engine",
    description: "Tiered commission calculation and automated payout scheduling for agents.",
    businessGoal: "Remove manual commission calculation errors.",
    product: "agents",
    team: "Backend Team",
    ownerId: "u2",
    status: "todo",
    priority: "medium",
    progress: 10,
    start: [2026, 11, 8],
    end: [2026, 12, 2],
    version: "v2.0",
    taskCount: 6,
  },
  {
    id: "agt-appredesign",
    title: "Agent App Redesign",
    description: "Refreshed agent-facing app UI focused on faster cash-in/cash-out flows.",
    businessGoal: "Reduce average transaction time per agent visit.",
    product: "agents",
    team: "Design Team",
    ownerId: "u6",
    status: "backlog",
    priority: "low",
    progress: 8,
    start: [2026, 12, 3],
    end: [2026, 12, 23],
    version: "v2.0",
    taskCount: 4,
  },

  // Mizaniya Market
  {
    id: "mkt-catalog",
    title: "Marketplace Catalog",
    description: "Product catalog infrastructure with categories, search and merchant listings.",
    businessGoal: "Launch the first version of Mizaniya Market marketplace.",
    product: "market",
    team: "Backend Team",
    ownerId: "u2",
    status: "in_progress",
    priority: "high",
    progress: 35,
    start: [2026, 10, 15],
    end: [2026, 11, 20],
    version: "v1.0",
    taskCount: 7,
  },
  {
    id: "mkt-storefront",
    title: "Merchant Storefronts",
    description: "Customizable storefront pages for merchants selling on the marketplace.",
    businessGoal: "Give merchants a branded presence to drive repeat customers.",
    product: "market",
    team: "Frontend Team",
    ownerId: "u8",
    status: "todo",
    priority: "medium",
    progress: 12,
    start: [2026, 11, 15],
    end: [2026, 12, 10],
    version: "v1.0",
    taskCount: 5,
    dependencies: ["mkt-catalog"],
  },
  {
    id: "mkt-orders",
    title: "Order Management",
    description: "End-to-end order lifecycle tracking from checkout to fulfillment.",
    businessGoal: "Support the marketplace beta launch with reliable order tracking.",
    product: "market",
    team: "Backend Team",
    ownerId: "u3",
    status: "backlog",
    priority: "medium",
    progress: 5,
    start: [2026, 12, 5],
    end: [2026, 12, 28],
    version: "v1.0",
    taskCount: 6,
    dependencies: ["mkt-catalog"],
  },
];

const statusPool = [
  "Backlog",
  "Todo",
  "In Progress",
  "Review",
  "QA Testing",
  "Ready Deployment",
] as const;

function mockTasksFor(seed: Seed): RoadmapItem["tasks"] {
  return Array.from({ length: seed.taskCount }).map((_, i) => ({
    id: `${seed.id}-t${i + 1}`,
    name: `${seed.title} — subtask ${i + 1}`,
    status:
      i / seed.taskCount < seed.progress / 100
        ? "production"
        : (statusPool[i % statusPool.length]
            .toLowerCase()
            .replace(/ /g, "_") as RoadmapItem["status"]),
    assignee: owner(seed.ownerId).name,
    dueDate: iso(...seed.end),
  }));
}

function mockCommentsFor(seed: Seed): RoadmapItem["comments"] {
  if (seed.progress < 20) return [];
  return [
    {
      id: `${seed.id}-c1`,
      author: owner(seed.ownerId).name,
      text: "Kicked off development, initial API contracts agreed with backend.",
      createdAt: iso(...seed.start),
    },
    ...(seed.progress > 50
      ? [
          {
            id: `${seed.id}-c2`,
            author: "Karim S.",
            text: "QA pass scheduled once the current sprint's tasks move to review.",
            createdAt: iso(seed.start[0], seed.start[1], seed.start[2] + 10),
          },
        ]
      : []),
  ];
}

export const MOCK_ROADMAP_ITEMS: RoadmapItem[] = seeds.map((seed) => ({
  id: seed.id,
  clickupTaskId: `mock-${seed.id}`,
  clickupUrl: `https://app.clickup.com/t/mock-${seed.id}`,
  title: seed.title,
  description: seed.description,
  businessGoal: seed.businessGoal,
  product: seed.product,
  team: seed.team,
  owner: owner(seed.ownerId),
  status: seed.status,
  priority: seed.priority,
  progress: seed.progress,
  startDate: iso(...seed.start),
  dueDate: iso(...seed.end),
  version: seed.version,
  taskCount: seed.taskCount,
  tasks: mockTasksFor(seed),
  comments: mockCommentsFor(seed),
  attachments:
    seed.progress > 40
      ? [{ id: `${seed.id}-a1`, name: "spec.pdf", url: "#" }]
      : [],
  dependencies: seed.dependencies ?? [],
  isMock: true,
}));

export const MOCK_MILESTONES: Milestone[] = [
  { id: "ms-kyc2", title: "KYC Phase 2", date: iso(2026, 10, 10), product: "mobile", emoji: "🚀" },
  { id: "ms-paylinks", title: "Payment Links", date: iso(2026, 10, 25), product: "partner", emoji: "🚀" },
  { id: "ms-mobile13", title: "Mobile App v1.3 Release", date: iso(2026, 10, 28), product: "mobile", emoji: "🚀" },
  { id: "ms-merchantdash", title: "Merchant Dashboard", date: iso(2026, 11, 5), product: "partner", emoji: "🚀" },
  { id: "ms-partnerlaunch", title: "Partner Platform Launch", date: iso(2026, 11, 15), product: "partner", emoji: "🚀" },
  { id: "ms-gatewaybeta", title: "Payment Gateway Beta", date: iso(2026, 12, 1), product: "gateway", emoji: "🚀" },
  { id: "ms-satim", title: "SATIM Integration", date: iso(2026, 11, 20), product: "gateway", emoji: "🚀" },
  { id: "ms-production", title: "Production Release", date: iso(2026, 12, 20), emoji: "🚀" },
];
